// <auto-generated />
namespace DataLinker.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_OrganisationLicenses_To_Support_CustomLicenses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_OrganisationLicenses_To_Support_CustomLicenses));
        
        string IMigrationMetadata.Id
        {
            get { return "201802202319223_Update_OrganisationLicenses_To_Support_CustomLicenses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
