// <auto-generated />
namespace DataLinker.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UpdateLicenseAgreementsToUseConsumerProviderRegistrations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdateLicenseAgreementsToUseConsumerProviderRegistrations));
        
        string IMigrationMetadata.Id
        {
            get { return "201904180012041_Update-LicenseAgreements-To-Use-Consumer-Provider-Registrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
